[tool.poetry]
name = "{{ $base }}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
cdktf = "~=0.19.2"
pytest = "~=7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
